---
- name: install xserver
  apt: 
    name: 
    - xserver-xorg
    - xserver-xorg-core
    - xfonts-base
    - xinit
    - x11-xserver-utils
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_xserver

- name: install fonts
  apt: 
    name: 
    - fonts-ipa*
    - fonts-noto
    - fonts-ricty-diminished
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_fonts

- name: install xfce
  apt: 
    name: 
    - xubuntu-desktop
    - xfce4-goodies
    - pavucontrol
    - pulseaudio
    - xfce4-pulseaudio-plugin
    - lightdm
    - lightdm-gtk-greeter
    - firefox
    - firefox-locale-en
    - firefox-locale-ja
    - chromium-browser
    - plymouth-x11
    - gimp
    - inkscape
    - libreoffice
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop

- name: greeter setting
  lineinfile: >
    dest="/usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf"
    line="{{ item }}"
  with_items:
    - "allow-guest=false"
    - "greeter-hide-users=true"
    - "greeter-show-manual-login=true"

