---
- name: install xserver
  apt: 
    name: 
    - xserver-xorg
    - xserver-xorg-core
    - xfonts-base
    - xinit
    - x11-xserver-utils
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_xserver

- name: install fonts
  apt: 
    name: 
    - fonts-ipa*
    - fonts-noto
    - fonts-ricty-diminished
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_fonts

- name: install xfce
  apt: 
    name: 
    - xubuntu-desktop
    - xfce4-goodies
    - lightdm
    - lightdm-gtk-greeter
    - firefox
    - firefox-locale-en
    - firefox-locale-ja
    - plymouth-x11
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: install_desktop

- name: greeter setting
  lineinfile: >
    dest="/usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf"
    line="{{ item }}"
  with_items:
    - "allow-guest=false"
    - "greeter-hide-users=true"
    - "greeter-show-manual-login=true"

- name: keyboard setting
  lineinfile: >
    dest="/etc/default/keyboard"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: "XKBMODEL=", line: 'XKBMODEL="{{ keyboardmodel }}"' }
    - { regexp: "XKBLAYOUT=", line: 'XKBLAYOUT="{{ keyboardlayout }}"' }
    - { regexp: "XKBVARIANT=", line: 'XKBVARIANT=""' }

- name: grub setting
  lineinfile: >
    dest="/etc/default/grub.d/50-cloudimg-settings.cfg"
    regexp="GRUB_CMDLINE_LINUX_DEFAULT.*"
    line='GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  register: grub_config

- name: update grub
  command: update-grub
  when: grub_config is changed

- name: update initramfs
  command: update-initramfs -u -k all
  when: grub_config is changed

